import Head from "next/head";
import ServiceCard from "../components/servcieCard";
import { services } from "../info/data";
import { motion } from "framer-motion";
import { fadeInUp, routeAnimations, stagger } from "../components/animations";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className="flex flex-col px-6"
        // variants={routeAnimations}
        // initial="initial"
        // animate="animate"
        // exit="exist"
      >
        <h5 className="my-3 font-medium">
          I&apos;m a Front-End Developer. I have serious passion for UI effects,
          animations and creating intuitive, dynamic user experiences.
          Let&apos;s make something special.
        </h5>
        <div
          className="p-4   mt-5 py-[21px] bg-gray-400 dark:bg-dark-100 "
          style={{ marginLeft: "-1.5rem", marginRight: "-1.5rem" }}
        >
          <div>
            <h6 className="my-3 tracking-wide text-xl font-bold">
              What I Offer
            </h6>
          </div>
          <motion.div
            className="grid lg:grid-cols-2 gap-6"
            variants={stagger}
            initial="initial"
            animate="animate"
          >
            {services.map((service) => {
              return (
                <motion.div
                  className="bg-gray-200 dark:bg-dark-300 rounded-lg lg:col-span-1"
                  key={Math.random()}
                  variants={fadeInUp}
                >
                  <ServiceCard service={service} />
                </motion.div>
              );
            })}
          </motion.div>
        </div>
      </div>
    </div>
  );
}
